
server:
  port: 8105
  servlet:
    context-path: /tuition

spring:
  application:
    name: CMS-Class-Location

  datasource:
    url: jdbc:mysql://bd3dabe003b1d4:d3f6ae8c@us-cdbr-east-06.cleardb.net/heroku_b2917d10e1448b0?reconnect=true
#    username: root
#    password: Dev@#$123
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update


eureka:
  client:
    serviceUrl:
      defaultZone: https://cms-discovery.herokuapp.com/eureka
  instance:
    preferIpAddress: true

security:
  key: accessKey


