
server:
  port: 8105

spring:
  application:
    name: CMS-Class-Location

  datasource:
    url: jdbc:mysql://localhost:3306/cms_tuition_class
    username: root
    password: Dev@#$123
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: create

