
server:
  port: 8105

spring:
  application:
    name: CMS-Class-Location

eureka:
  client:
    serviceUrl:
      defaultZone: https://cms-discovery.herokuapp.com/eureka
  instance:
    preferIpAddress: true

  datasource:
    url: jdbc:mysql://ba357867db0b80:d43777ed@us-cdbr-east-06.cleardb.net/heroku_93837273fed35d1?reconnect=true
#    username: root
#    password: Dev@#$123
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update

